### ISSUE TITLE
Manifest Issue

### ISSUE THREAD

**Issue by Jakosaur** [alexanderwe/the-traveler#30] opened 2018-09-01 15:53 UTC
Can download the manifest fine, but then when I then try to download the manifest again I get

Error: EPERM: operation not permitted, open 'mylongfilepath\world_sql_content_d122ea6e6d07e448d34868985f7a9cb9.content.zip'

**Comment by alexanderwe** [comment] 2018-09-02 10:59
Hey @Jakosaur, 

thanks for submitting this issue. I tried to reproduce what you said, but I was unable to get the error you posted. Can you give me a short code block in which your error appears and which I can try to run to figure out what the problem is ? That would be very nice

**Comment by Jakosaur** [comment] 2018-09-02 11:10
I was using a different way but I thought it wasn't working, but even with the example given, an error appears 

`traveler.getDestinyManifest().then(result => {
            traveler.downloadManifest(result.Response.mobileWorldContentPaths.en, './manifest.content').then(filepath => {
                const manifest = new Manifest(filepath);
                manifest.queryManifest('SELECT name FROM sqlite_master WHERE type="table"').then(queryResult => {
                    console.log(queryResult);
                }).catch(err => {
                    console.log(err);
                });
            }).catch(err => {
                console.log(err);
            })
        })`

**Comment by alexanderwe** [comment] 2018-09-02 11:32
I assume you are on Windows right ? Which version of the-traveler are you using ?

**Comment by Jakosaur** [comment] 2018-09-02 11:56
Yeah Windows. v-0.7.1

On 2 Sep 2018, at 12:32, Alexander Weiß <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume you are on Windows right ? Which version of the-traveler are you using ?

**Comment by Jakosaur** [comment] 2018-09-03 07:39
I've done a new Node Project from scratch, all I did was the normal `npm init`, `npm install the-traveler` & `npm install sqlite3`

Then ran this [code](https://gist.github.com/Jakosaur/24e21c30cfc91a3013c7723b5785ccc7)

**Comment by alexanderwe** [comment] 2018-09-03 12:31
Thanks for the code snippet. I was able to reproduce the issue on a windows machine. 

The idea was to unzip the zip file and if it is unzipped delete it right away, leaving the directory with the unzipped Sqlite3 database. I will investigate what exactly is happening there

**Comment by alexanderwe** [comment] 2018-09-03 13:06
I am not sure how fast I can get a solution for this. Feel free to also investigate the issue on your own. I assume it must be somewhere in those lines https://github.com/alexanderwe/the-traveler/blob/master/src/Traveler.ts#L1084-L1094. It seems I try to open the .zip but is not there. 

I assume the following happens:

1. Download .zip
2. Unzip it
3. Delete .zip
4. Somehow do not download it again
5. Try to open .zip but is deleted from the previous call

Also be aware to not post your API key publicly

**Comment by Jakosaur** [comment] 2018-09-03 13:09
Thanks for pointing my key is on there haha, I even made a note to remove it before uploading the code. At least its a new key I made this morning

**Comment by alexanderwe** [comment] 2018-09-05 20:14
Resolved with pull-request #31 
Thanks again for investigating and resolving this issue. Helps a lot 👍 
I will publish a new version with your fix to npm

**Closed by alexanderwe** 2018-09-05 20:14 UTC
